### PR TITLE
Deprecate Interaction API, to be replaced by Actions API

### PR DESCRIPTION
**Pull request by peternandersson**
This PR removes the Interaction API, since we're intending on replacing this feature with the new Actions API in the next minor version release.

### CODE REVIEW

**Review by Pearce-Ropion — DISMISSED** [review]
This should be a breaking change with a semver bump. We should release it with plugins.

**Comment by Pearce-Ropion** [comment]
Actually, can you change the base branch to the plugins branch?

**Comment by peternandersson** [comment]
> Actually, can you change the base branch to the plugins branch?

Which branch? The plugin-actions branch? The change shouldn't be breaking until we publish to npm unless I'm missing something, and we could release to 1.1.0 to avoid the issue or just deprecate the functionality instead of removing it altogether - I'd probably favor the former.

**Comment by peternandersson** [comment]
Going to replace this with a deprecation warning instead of removing altogether, will re-request once the changes are pushed.

**Review by Pearce-Ropion — APPROVED** [review]

**Pull request merged**
